### ISSUE TITLE
Sensor type listed as pressure rather than accelerometer.

### ISSUE THREAD

**Issue by WhiskeyTuesday** [adafruit/Adafruit_ADXL345#18]
I submitted a pull request with the fix a few years back. Hoping to draw your attention to it.

**Comment by microbuilder** [comment]
Thanks, and sorry for the incredibly slow reply. Merged!

**Comment by WhiskeyTuesday** [comment]
This was actually the first PR I ever made anywhere. I think it was before I'd ever read a programming book.
