### ISSUE TITLE
Wrong function name: displaySetRange

### ISSUE THREAD

**Issue by Oehoeboeroe** [adafruit/Adafruit_ADXL345#9]
althought between comments, the function displaySetRang doesn't exits.
Please change to accel.setRange

  accel.setRange(ADXL345_RANGE_16_G);
  // displaySetRange(ADXL345_RANGE_8_G);
  // displaySetRange(ADXL345_RANGE_4_G);
  // displaySetRange(ADXL345_RANGE_2_G);

**Comment by microbuilder** [comment]
Fixed in #12
